
name: PR Commenter

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment-on-pr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR was just opened
        run: echo ::set-output name=IS_OPENED::$(if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.action }}" == "opened" ]; then echo "true"; else echo "false"; fi)
        id: check-opened
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const greeting = ${{ steps.check-opened.outputs.IS_OPENED }} ? "Hello World! and opened" : "updated";
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: greeting,
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
